### ISSUE TITLE
翻译内容不完整？

### ISSUE THREAD

**Issue by rayworks** [leeowenowen/jni-examples#1]
Hi @leeowenowen , 很感谢您在本书翻译和代码方面做的工作。想确认一点的是从[看云](https://www.kancloud.cn/owenoranba/jni/120520) 上看到，翻译的内容从“一些JNI的特性”这章开始就没有了，所以当前的状态是整本书的翻译还没有完结吗？
如有更新的链接，还请不吝分享出来。谢谢！

**Comment by leeowenowen** [comment]
多谢支持， 不过那个翻译过去很久，都没维护了，记得当时是差不多翻译完了，可能是我记错了吧，原版的英文其实也是挺好理解的，你可以找找原书看下，有问题我们可以讨论。

**Comment by Freedom000** [comment]
我也在找更新版 貌似没有翻译完整 只翻译到了The Invocation Interface这章~还是希望作者能够翻译完~
